### ISSUE TITLE
NameError: uninitialized constant SolrWrapper

### ISSUE THREAD

**Issue by gireeshkumar** [samvera/hydra#139]
I am getting error when running  "bin/rails hydra:server"

> root@92bce299f2d1:/opt/myapp01# bin/rails hydra:server
rails aborted!
NameError: uninitialized constant SolrWrapper
/usr/local/rvm/gems/ruby-2.4.0/gems/active-fedora-11.4.0/lib/active_fedora/rake_support.rb:17:in `with_server'
/usr/local/rvm/gems/ruby-2.4.0/gems/hydra-core-10.5.0/lib/tasks/hydra.rake:6:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/usr/local/rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/opt/myapp01/bin/rails:9:in `require'
/opt/myapp01/bin/rails:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/opt/myapp01/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => hydra:server
(See full trace by running task with --trace)

**Comment by straccers** [comment]
did you (or anyone else) ever find the solution for this?

**Comment by cjcolvar** [comment]
This should work if you add `gem 'solr_wrapper'` to your `Gemfile` and run `bundle install`.

**Comment by jcoyne** [comment]
That should have been added to the gemfile when you ran the blacklight generators (via the hydra generators) https://github.com/projectblacklight/blacklight/blob/3370b957eb302e9e64c0b92b7fe63b6af972b239/lib/generators/blacklight/solr_generator.rb#L17

**Comment by straccers** [comment]
thanks justin. I think I found the underlying cause, which was that ffi was
not installing properly. Googling around, I found that the solution to this
was to run  apt-get install libffi-dev, however I needed to add this to the
bootstrap.sh - when I tried to add it after the vm was created, then run
bundle update again, even with a completely clean build,  I  got the
solrwrapper error. But adding it to the bootstrap fixed it and the
hyrax-demo then ran as expected without further bad things happening



Regards
Peri Stracchino
University of York Digital Library Technical Team

**Comment by avowkind** [comment]
As of Feb 2019 the Vagrant install (on OSX) shows this problem. 
I added the line `gem 'solr_wrapper'` to your `Gemfile` and run `bundle install` and this appears to have fixed it.  Can the Vagrant file be updated to fix this?

**Comment by no-reply** [comment]
@avowkind this project is unmaintained. It was previously a meta-distribution of other Samvera project software. 

I doubt anyone would object to work updating the Vagrantfile, but it seems likely that you are looking for one or more of the projects in https://github.com/samvera.

**Comment by avowkind** [comment]
OK Thanks.  Is there anywhere I can go to have a demo or sandbox play with Samvera without having to launch my own copy?

Ngā mihi, Andrew

**Comment by rotated8** [comment]
Hi Andrew, [Nurax](https://nurax-dev.curationexperts.com/) is a sandbox environment that has the latest (unreleased) code for Hyrax.

**Comment by avowkind** [comment]
Thats perfect - thanks.
